AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 Instance

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0bb84b8ffd87024d8

Outputs:
  InstanceName:
    Value: !Ref Instance
