AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 Instance

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: ' Enter instance type t2.micro, t2.small, t2.medium'

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: ami-0bb84b8ffd87024d8

Outputs:
  InstanceName:
    Value: !Ref Instance

